/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buku;

import java.sql.*;
import java.text.Format;
import javax.swing.*;
import javax.swing.table.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author user
 */
public class perpustakaan extends javax.swing.JFrame {
public String tgl_peminjaman;
public String tgl_pengembalian;

    private void kosongkan_form(){
        nim.setText(null);
        nama.setText(null);
        jurusan.setText(null);
        jbuku.setSelectedItem(this);
        peminjaman.setDate(null);
        pengembalian.setDate(null);
    }
    
    private void bersih(){
        nama.setText("");
        jbuku.setSelectedItem("");
        nim.setText("");
        peminjaman.setDate(null);
        pengembalian.setDate(null);
        jurusan.setText("");
        nim.requestFocus();
    }
    
    /**
     * Creates new form perpustakaan
     */
    public perpustakaan() {
        initComponents();
        tampil_buku();
    
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jurusan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbuku = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        peminjaman = new com.toedter.calendar.JDateChooser();
        pengembalian = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnedit = new javax.swing.JButton();
        btnpinjam = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PEMINJAMAN BUKU PERPUSTAKAAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("NIM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 30, -1));

        nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimActionPerformed(evt);
            }
        });
        getContentPane().add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 84, 164, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("NAMA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 122, 164, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("JURUSAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 60, -1));

        jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanActionPerformed(evt);
            }
        });
        getContentPane().add(jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 160, 164, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("JENIS BUKU");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, 80, -1));

        jbuku.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATIMATIKA DASAR", "MATIMATIKA DISKRIT", "BIOLOGI", "CLOUD", "ENGINEERING", "DATABASE & WEB", "JAVA", "MYSQL JAVA", "BAHASA INGGRIS", "AGAMA", "PKN", "SIKSA NERAKA" }));
        getContentPane().add(jbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 198, 164, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("PEMINJAMAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 90, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("PENGEMBALIAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 125, 100, -1));

        peminjaman.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                peminjamanPropertyChange(evt);
            }
        });
        getContentPane().add(peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 84, -1, -1));

        pengembalian.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pengembalianPropertyChange(evt);
            }
        });
        getContentPane().add(pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 122, -1, -1));

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        tabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabel1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 333, 677, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btnedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnpinjam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnpinjam.setText("PINJAM");
        btnpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpinjamActionPerformed(evt);
            }
        });

        btnbatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbatal.setText("BATAL");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btncari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnhapus)
                .addGap(18, 18, 18)
                .addComponent(btnedit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpinjam))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnedit)
                            .addComponent(btnpinjam)
                            .addComponent(btnbatal)
                            .addComponent(btnhapus)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncari))))
                .addContainerGap(450, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusanActionPerformed

    private void btnpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpinjamActionPerformed
try{
            String sql="insert into tbbuku values('"
                    +nim.getText()+"','"
                    +nama.getText()+"','"
                    +jurusan.getText()+"','"
                    +jbuku.getSelectedItem()+"','"
                    +tgl_peminjaman+"','"
                    +tgl_pengembalian+"')";
            java.sql.Connection conn = (java.sql.Connection)buku.koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil dipinjam");
            bersih();
            tampil_buku();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal dipinjam");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnpinjamActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
//        nama.setText("");
//        jbuku.setSelectedItem("");
//        nim.setText("");
//        peminjaman.setDate(null);
//        pengembalian.setDate(null);
//        jurusan.setText("");
//        nim.requestFocus();     

        bersih();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void peminjamanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_peminjamanPropertyChange
        if(peminjaman.getDate()!=null){
    SimpleDateFormat format=new SimpleDateFormat ("yyyy-MM-dd");
    tgl_peminjaman=format.format(peminjaman.getDate());
    }
    }
    public void tampil_buku(){
    DefaultTableModel tabel=new DefaultTableModel();
    tabel.addColumn("NIM");
    tabel.addColumn("NAMA");
    tabel.addColumn("JURUSAN");
    tabel.addColumn("JENIS BUKU");
    tabel.addColumn("PEMINJAMAN");
    tabel.addColumn("PENGEMBALIAN");
        try{
            java.sql.Connection conn=(java.sql.Connection)buku.koneksi.configDB();
            String sql = "select *from tbbuku"  ;
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while(rs.next()){
                tabel.addRow(new Object[]{
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            rs.getString(5),
            rs.getString(6)});
            }
                tabel1.setModel(tabel);
            
        }
                catch (Exception e){
                }
    }//GEN-LAST:event_peminjamanPropertyChange

    private void pengembalianPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pengembalianPropertyChange
if(pengembalian.getDate()!=null){
    SimpleDateFormat format=new SimpleDateFormat ("yyyy-MM-dd");
    tgl_pengembalian=format.format(pengembalian.getDate());
    }
    }//GEN-LAST:event_pengembalianPropertyChange

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
try{
            String sql="insert into tbbuku values('"
                    +nim.getText()+"','"
                    +nama.getText()+"','"
                    +jurusan.getText()+"','"
                    +jbuku.getSelectedItem()+"','"
                    +tgl_peminjaman+"','"
                    +tgl_pengembalian+"')";
                 java.sql.Connection conn=(java.sql.Connection)buku.koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            bersih();
            tampil_buku();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tabel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabel1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel1KeyTyped

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel1MouseClicked

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
try {
    java.sql.Connection conn=(java.sql.Connection)buku.koneksi.configDB();
    String sql = "Select * from tbbuku where nim='"+cari.getText()+"' or nama='"+cari.getText()+"'";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    ResultSet rs = pst.executeQuery(sql);
    if (rs.next()){
        nim.setText(rs.getString(1));
        nama.setText(rs.getString(2));
        jurusan.setText(rs.getString(4));
        jbuku.setSelectedItem(rs.getString(3));
        peminjaman.setDate(rs.getDate(5));
        pengembalian.setDate(rs.getDate(5));
        JOptionPane.showMessageDialog(null,"Data tbbuku : "
        + cari.getText() + " ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
    }
} catch (Exception e){}
cari.requestFocus();
    }//GEN-LAST:event_btncariActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
try{
    java.sql.Connection conn=(java.sql.Connection)buku.koneksi.configDB();
    String sql = "delete from tbbuku where nim='"+nim.getText()+"' ";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.executeUpdate(); JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
    bersih();
    tampil_buku();
    }
catch (Exception e){
JOptionPane.showMessageDialog(null,"Proses Penghapusan Gagal");
System.out.println(e.getMessage());
}
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnpinjam;
    private javax.swing.JTextField cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jbuku;
    private javax.swing.JTextField jurusan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private com.toedter.calendar.JDateChooser peminjaman;
    private com.toedter.calendar.JDateChooser pengembalian;
    private javax.swing.JTable tabel1;
    // End of variables declaration//GEN-END:variables
}
